services:
    wardormeur.anoncache.controller:
        class: wardormeur\anoncache\controller\main
        arguments:
            - '@config'
            - '@controller.helper'
            - '@template'
            - '@user'
    wardormeur.anoncache.listener:
        class: wardormeur\anoncache\event\main_listener
        arguments:
            - '@controller.helper'
            - '@template'
            - '@auth'
        tags:
            - { name: event.listener }
